### ISSUE TITLE
BerryBoot P2 - Problems with ISCSI Target

### ISSUE THREAD

**Issue by peter0123** [maxnet/berryboot#132] opened 2015-02-06 14:49 UTC
Berryboot say always, check Target Settings.
= NO ISCSI!!

**Comment by lennvilardi** [comment] 2015-02-09 21:46
+1

**Comment by maxnet** [comment] 2015-02-11 01:37
http://downloads.sourceforge.net/project/berryboot/berryboot-20150211-pi2-only.zip

Can you try if this one works better?

**Comment by peter0123** [comment] 2015-02-11 05:03
Moment
Am 11.02.2015 02:37 schrieb "maxnet" notifications@github.com:

**Comment by peter0123** [comment] 2015-02-11 05:16
It is a litttle bit slower. Connect to target, Format, Mount.. 10-12
seconds on pi2.
Old one i think, 4-5 seconds with pi1.

But all OK! THX!
Am 11.02.2015 02:37 schrieb "maxnet" notifications@github.com:

**Comment by maxnet** [comment] 2015-02-11 11:14
Yes, also seems to take longer to get the network link itself up.
Not sure if it's Pi 2 specific, or kernel version specific though.

Anyway, closing this.

**Closed as completed by maxnet** 2015-02-11 11:14 UTC

**Comment by peter0123** [comment] 2015-02-11 15:14
After 3 boots.. Berryboot menu... Connection to iSCSI San

... And freeze..
Am 11.02.2015 12:14 schrieb "maxnet" notifications@github.com:

**Comment by lennvilardi** [comment] 2015-02-13 20:35
A little longer but all is fine now :) Thanks Maxnet

**Comment by peter0123** [comment] 2015-02-13 21:42
update? my problem was, he lost the network... then he found no iSCSI and freeze... sry ;(
But the connection at the begin is slow..

**Comment by lennvilardi** [comment] 2015-02-13 21:54
Finally not fine :
If I reboot the PI2 : I get Connecting to iSCSI SAN searching, then Error connecting to server.
I press ok waiting for data partition iscsi, Data is not at iscsi. Searching other partitions. Cannot find my data partition :-( 
And finally I'm in the emergency recovery shell.
I need to unplug the power cable to reboot the PI2

**Comment by lennvilardi** [comment] 2015-02-21 21:03
any update ? still useless ...

**Comment by peter0123** [comment] 2015-02-21 21:44
I think you have no network. Or the PI can not reach ISCI Server. I have no problem....

Check cmdline.txt

DATADEV=ISCI
QMAP=DE
You have this entrys?

I delete the entry:

smsc95.TURBO_MODE=N

Set a fix ip, ping your berry from other pc. 
Check iscsi.sh. all correct?

Open: slow network at begin.

**Comment by lennvilardi** [comment] 2015-03-01 22:31
datadev=iscsi ok
qmap=fr ok
I delete the entry you give
ip is fixed no dhcp
iscsi.sh is empty from the berryboot interface but when I load the card on the pc and open it on my desktop it gives :
/sbin/iscsistart -i "iqn.blahblah" -g 1 -t "iqn.balablahaha" -a "192.168.1.X"
still got error connecting to server when rebooting :(

**Comment by peter0123** [comment] 2015-03-01 23:05
=> the first iqn is very important. I do not know if it is specifically related to something. you have no authentication... -u -w .... 

/sbin/iscsistart -i "iqn.2012-08.com.berryboot:myPi" -g 1 -t "iqn.2000-01.com.synology-iSCSI:VIrtualDisk.01" -a "192.168.1.120" -u "yourlogin" -w "yourpassword"

my cmdline.txt: 
cgroup_enable=memory elevator=deadline quiet bootmenutimeout=3 datadev=iscsi qmap=de

my uEnv.txt
 datadev=iscsi qmap=de

my config.txt
disable_overscan=1
start_x=1
force_turbo_1
arm_freq=1100
core_freq=600
sdram_freq=500
over_voltage=8
over_voltage_sdram=4
gpu_mem=64
kernel=kernel_rpi2_aufs.img
initramfs berryboot.img

=> and you have really the last image? because I had the same problem as you, as I usethe first Pi2 image.
=> and you've really tried to ping the pi from another computer?
=> test the scsci under windows... "iSCSI-Initiator" can you find your target, can you connect it with a windows client..

**Comment by lennvilardi** [comment] 2015-03-15 13:58
with your settings I've got plenty of errors while booting OpenElec :(
SQUASHFS error : Unable to reda data...

**Comment by peter0123** [comment] 2015-03-15 14:10
I use raspbian :) but that info help you..
Am 15.03.2015 14:58 schrieb "lennvilardi" notifications@github.com:

**Comment by lennvilardi** [comment] 2015-03-15 14:11
My Pi2 doesn't like yours overclocking settings

**Comment by lennvilardi** [comment] 2015-03-15 14:16
I disable the overclocking put the gpu_mem to 320
iscsi.sh is correct, uEnv is the same
I use the last version, I can ping and I can mount the iscsi under windows
I still got errors :( try on 2 differents sd card
Why do you use cgroup_enable ?

**Comment by lennvilardi** [comment] 2015-03-16 13:02
It seems that an rpi-update on the pi2 made the trick :) but now CEC is not working anymore :( (it was working on my previous pi)

**Comment by lennvilardi** [comment] 2015-03-20 15:52
After a few days still got problems with iscsi :(

**Comment by CreatoX** [comment] 2015-09-16 14:40
Hi all,

I saw this issue is closed, but did not find a solution to the problem.

As lennvilardi  described on Fab 13, the exact same issue is happening on my Pi.
Also a Pi 2 with a wired connection to a Synology NAS. The first boot (after power off) is always good and I can boot into several Operating Systems. RasPlex, OpenElec, they all worked fine.
But after a reboot somehow the iSCSI connection cannot be made resulting errors and finally the emergency console. Only a power off and power on resolves this issue.

Tried several settings in berryboot and iSCSI connection (with or without password), nothing worked. 

Is there something not mentioned  I can try to fix it?

Edit: 
I'm using berryboot-20150808-pi2-only.zip and just a new version is released: berryboot-20150916-pi2-only.zip. I will try the new version and let you know if there is any difference.

**Comment by lgb-this** [comment] 2016-01-30 13:11
I installed the latest BerryBoot and Raspbian. After a reboot command, i get always:

"error connecting to server"

The Raspberry Pi 2 boots from iSCSI only after power off and power on. What do i have to change, that the system can boot after a reboot command ?

**Comment by vento66** [comment] 2016-02-14 09:37
The problem is, the Raspi is to fast. The conection to the iscsi target is still available. It takes 5 sec longer to disconect. So the Raspi can not connect to the iscsi.

**Comment by lgb-this** [comment] 2016-02-14 16:01
And how can i delay the start of BerryBoot, that the connection to the iSCSI after a reboot will be successful ?

**Comment by maxnet** [comment] 2016-02-14 17:06
Can't you configure your iSCSI SAN to allow multiple simulatenous connections instead?

**Comment by lgb-this** [comment] 2016-02-14 18:04
Bingo ! I shotdown my RPI2 and changed the setting in my QNAP. Now i can reboot the RPI2 without any problems. Thanks for your help.

**Comment by paconio** [comment] 2016-10-23 14:09
Hello mates.
I don´t know If I have the same troubles than you.
I´ve pi3 and micro server G8
I have tried to install several images through berryboot 20160930-pi2-pi3 version ...
I´m using for that wifi connection ...
In the step where I put all the information (target iqn and ip server) I find the follow message:
"Error zero´ing MBR/GPT. SD card may be broken or adversiting wrong capacity" 
After that appears a ISCN drive and ask me if I want to format that:
sda: ISCI Storage ----> Formatting data partition (ext4)
When the formatting process finish, We chose a image to installin the ISCI storage (for exampe retropie), but when The Pi reboots .... this message appears "waiting for data partition sdb2? and at the end ... "Cannot find my data partition :-( . and starts the emergency recovery sistem.

I can´t solve that problem ... I have used 3 differents micro sd cards and the same error ...
Somebody can help me???

Thank you in advance!!!

**Comment by edegraaff** [comment] 2017-03-17 21:03
Hi, i have the same problem, i am puzzling for weeks now, cant find the reason why the iscsi device is not connecting. It seems to me the installation and configuration files are not written to the sd card, i can;t find any iscsi device settings in the config files. I have tried, wifi, direct cable, dhcp and static ip. It seems the network is not up and the berryboot connect to iscsi is already running. I will try to do some network sniffing, the boot proces for mounting iscsci for synology nas seems broke for the pi 3

**Comment by maximkrusina** [comment] 2017-04-09 21:35
For some reason, iscsi is nit writted into config.
For me, editing two files fixed the issue:
uEnv.txt > change **datadev=sda2** to **datadev=iscsi**
cmdline.txt > change **datadev=sda2** to **datadev=iscsi**

**Comment by edegraaff** [comment] 2017-04-11 21:39
Yes latest build does work! thanks for fixing this one

**Comment by WaaromZoMoeilijk** [comment] 2017-08-17 19:08
Where should iscsi.sh reside? can't find it by searching: find /location/of/sd -iname iscsi.sh
Latest image won't load it at first boot. Made all the changes by hand now, but cant find where to specify the iscsi details.

**Comment by betchern0t** [comment] 2018-05-21 10:18
Still seeing this in the latest stable version of berryboot. raspberry pi3 against stock ubuntu 1804 server running tgt for the iscsi setup. It connects, begins to prepare the disk and then fails with the error: error zeroing the mbr/gpt: sd card may be broken... It does write what looks like a correct iscsi.sh and i added the datadev=iscsi tag to config.
