### ISSUE TITLE
use Os of berryboot with a gamepad

### ISSUE THREAD

**Issue by babarba** [maxnet/berryboot#114] opened 2014-08-27 07:44 UTC
Hello and Im so sorry for my bad English
Im would like choosing a Os of berryboot with my joystick, but only one my Keyboard or my mouse 
 works during the choice. How could I make reconnaitre my gamepad on the demarrage of the raspberry 
The idea is that I installed retropie 2 and openelec with demarrage at the end of 10s on openelec, and I shall like(love) if I want to play the games retro, to take just the joystick to choose
 thank you

**Comment by maxnet** [comment] 2014-08-29 16:22
Sorry, the user interface is currently not suitable for gamepads/joysticks.

Duplicate of #38

**Closed as completed by maxnet** 2014-08-29 16:22 UTC
Labels: duplicate
