### ISSUE TITLE
22/03/2018 version does not boot

### ISSUE THREAD

**Issue by vincentkenny01** [maxnet/berryboot#488] opened 2018-03-27 13:19 UTC
Hi,
I had to rebuild my pi and downloaded the 22-march-2018 version of berryboot. But it failed to boot with loads of errors. I had tried 3 times after reformatting the card and usb drive but no luck. Luckily I had an old version of berryboot and that seems to work fine. 

Anyone else had this issue? 

Also, where can i find the older versions of berryboot? Are they available?

V

**Comment by maxnet** [comment] 2018-03-27 13:27
Can you be a little bit more specific than "loads of errors"?
Got a photo?

Older versions are on Sourceforge: https://sourceforge.net/projects/berryboot/files/

**Comment by vincentkenny01** [comment] 2018-03-27 13:30
well I cannot reproduce the errors now as I have used an older version to restore but the errors mentioned stated "kernel failure" of some sort. I should have taken a photo but will keep that in mind next time. I was quite surprised to see the errors as I have not seen them before. you can close this comment if you wish and wait if anyone else comes across the same error. Mine is pi 2 model. 
Best,

V

**Comment by maxnet** [comment] 2018-03-27 15:38
Closing as errors are unspecified.

**Comment by vincentkenny01** [comment] 2018-03-27 18:26
![20180327_191357](https://user-images.githubusercontent.com/9219050/37986887-a7593fd2-31f4-11e8-96d6-18b270cecc14.jpg)
Here is th3 screenshot

**Comment by 0o0-TheDude-0o0** [comment] 2018-03-27 18:52
I can confirm the same behavior and errors. Kernel panics casuing system to fail post. Pi 3 B+ with latest berryboot. Issue happens randomly on boot. Can cut power and reboot with random success. This ticket should be re-opened.

**Comment by maxnet** [comment] 2018-03-27 18:56
Probably related to: https://github.com/raspberrypi/linux/issues/2450

**Comment by maxnet** [comment] 2018-03-29 22:57
Any better luch with 20180329?

**Comment by 0o0-TheDude-0o0** [comment] 2018-03-30 08:16
It appears to be working great now! Thank you!

**Comment by Lucky0005** [comment] 2018-03-31 08:06
what is final solution now?
I have same issue like on screen "Kernel panic" on my **RPi2** with the latest berryboot-**20180329**-pi2-pi3.zip and older version berryboot-**20180322**-pi2-pi3.zip too.

**Comment by symbios24** [comment] 2018-04-01 12:51
Same issue here on a fresh install with latest berryboot version 20180329 on a raspberry pi 3 (not 3b+)

**Comment by symbios24** [comment] 2018-04-02 06:29
Same issue here on a fresh install with latest berryboot version 20180329 on a raspberry pi 3 (not 3b+) 
Kernel panic message before berryboot loads is this going to be fixed?

**Comment by Lucky0005** [comment] 2018-04-03 14:54
I tried two microSD card 2 and 4GB from different producer, but with same result :(

**Comment by symbios24** [comment] 2018-04-03 15:50
its not a card problem its probably the kernel something with usb probably.

**Comment by symbios24** [comment] 2018-04-03 15:50
its not a card problem its the kernel something with usb probably.

**Comment by pzvalenta** [comment] 2018-04-06 08:57
After unplugging a wireless keyboard receiver it works fine. (20180405 pi2) Thanks symbios24.

**Comment by Lucky0005** [comment] 2018-04-06 11:08
I read some information about USB problem before, but on my side unplugging a wireless keyboard receiver on  20180322 and 20180329 didn´t helped.
So, if new version 20180405 working without wireless keyboard receiver, it is improvement, but it isn´t final 100% solution :( because I want to use wireless keyboard, without unplug/plug receiver.

**Comment by symbios24** [comment] 2018-04-06 11:41
Well all the keyboards are usb wireless or not, old keyboard with ps2 port can be only connected with with usb adapter,so whatever you use it goes to the usb anyway.i got an RC 12 Wireless Keyboard tiny and practical.

**Comment by Lucky0005** [comment] 2018-04-06 17:08
so right now I tested 20180405 and here is little progress, it is very random, 1 from 7 start of berryboot is successfully. Does not matter if I have plugged or unplugged dongle of usb wireless keyboard.

**Comment by symbios24** [comment] 2018-04-07 06:39
Lucky0005 what power supply do you have?

**Comment by Lucky0005** [comment] 2018-04-08 06:46
5V/2A, this adapter I'm using more than 2 years. I had instaled Berryboot with raspbian and openelec without problem. Because new version of Berryboot doesn't work on my side, I have on SD card only the latest  version Libreelec which work and boot fine.

**Comment by symbios24** [comment] 2018-04-08 07:03
it works ok ( for the  moments on me) 
try this: empty your memory card with sd-card formatter tool by setting from the options the format size adjustment to on.
after download this http://www.ridgecrop.demon.co.uk/guiformat.exe
and format your card by unchecking the quick format option (slow format) and press start
try this and then try the latest bb version.

**Comment by Lucky0005** [comment] 2018-04-08 13:10
I used quiformat.exe, but doesn´t helped still same error like on screenshot in this thread.

**Comment by symbios24** [comment] 2018-04-08 14:11
Try a different power supply and make sure you are using the latest version of berryboot

**Comment by symbios24** [comment] 2018-04-08 14:39
Try a different power supply and make sure you are using the latest version of berryboot,the old version gets this error whatever you do,only the last version fixes this.

**Comment by Lucky0005** [comment] 2018-04-08 18:57
only for you I did what you wanted :D
I took another power supply 5V/2A. Again I downloaded the latest images from official website: **berryboot-20180405-pi2-pi3.zip** and **berryboot-20180405-pi0-pi1-pi2-pi3.zip**, but still same bad result.
Only for my test I downloaded some older image **berryboot-20170527-pi2-pi3.zip** and my Rpi2 boot up three times in a row without any issue.

**Comment by symbios24** [comment] 2018-04-09 05:45
Thats strange,is the red light in your raspberry blinking sometimes?
Do you see the little thunder icon and the top right corner?
did you try only a normal usb mouse(not wireless) without a keyboard?

**Comment by Lucky0005** [comment] 2018-04-09 06:23
I will not alone, which have this problem, here is next #494 
Right now I´m not at home, and I´m not sure, but red LED still shine.
I didn´t have thunder icon, never. I´m sure that power supply is ok, no low power (I tried two pcs of PSU)
I tried without any KB or mouse, only Rpi+microSD+HDMI+LAN+microUSB power.

**Comment by symbios24** [comment] 2018-04-09 06:32
disconnect the lan cable and try again,do you have the rpi2 v1.1 or v1.2?

**Comment by symbios24** [comment] 2018-04-09 12:10
nobody told you to buy anything,and if i were you i would buy the official power supply its cheap and better than any other supply.

**Comment by Lucky0005** [comment] 2018-04-09 15:40
sorry, but I didn´t understand very well what you mean with your previous comment. Power supply I bought in set rpi+sd card+box from local eshop and I never had low power issue, but for your suggestion I tried another adapter from my mobile phone 5V/2A, and it didn´t helped, so I think that power supply issue we can exclude.

so back to your previous questions:
I have rpi 2 model B V1.1 (btw what is different between 1.1 and 1.2?)
I disconnected lan cable (only RPi+SDcard+HDMI+USB Power) and still same issue.

**Comment by symbios24** [comment] 2018-04-10 05:19
Try this versions berryboot-20180314-pi0-pi1-pi2-pi3.zip or berryboot-20180216-pi2-pi3.zip since you dont have an Rpi3b+ you dont need the latest version.

**Comment by Lucky0005** [comment] 2018-04-10 05:56
I need the latest version because, there was another issue with i2c #485 which was solved with 20180322 if I remember.

**Comment by symbios24** [comment] 2018-04-10 06:08
well if you can fix it manual as i see in this post: https://github.com/maxnet/berryboot/issues/485 
and put an older version will be fine

**Comment by Lucky0005** [comment] 2018-04-10 06:46
I didn't catch how to fix it manually in post #485.

**Comment by symbios24** [comment] 2018-04-10 14:08
here is what you do
put the latest version in a card and download these two older versions  berryboot-20180314-pi0-pi1-pi2-pi3.zip / berryboot-20180216-pi2-pi3.zip

open the most recent berryboot-20180314-pi0-pi1-pi2-pi3.zip and extract this three files in the card you just wrote with latest version:
kernel_rpi_aufs.img/kernel_rpi2_aufs.img / bcm2709-rpi-2-b.dtb
if the error appears again do the same with the oldest version berryboot-20180216

**Comment by Lucky0005** [comment] 2018-04-23 14:55
I did what you wanted. 
I used **berryboot-20180405-pi0-pi1-pi2-pi3.zip** and from this archive **berryboot-20180216-pi0-pi1-pi2-pi3.zip** I took 3 files **kernel_rpi_aufs.img/kernel_rpi2_aufs.img/bcm2709-rpi-2-b.dtb**.
Now berryboot boot without error and I can boot up to my libreelec, but LCD HD44780 via I2C bus doesn´t work. I think that problem is, that we used old kernel files where was some known bug with i2c.

**Comment by symbios24** [comment] 2018-04-25 06:28
strange coz the i2c files are on the overlays folder,put only the bcm2709-rpi-2-b.dtb file from the berryboot-20180405-pi0-pi1-pi2-pi3.zip archive and try again

**Comment by ALDamico** [comment] 2018-05-05 15:30
Same problem here. It _seems_ to be related to an insufficient amperage and removing all peripherals (except the hard drive, of course) may or may not help, but as others have pointed out, unplugging them doesn't seem to guarantee that the next boot is going to be successful. I'll probably downgrade my Berryboot to a previous version from now on because this renders my Pi pretty much unusable.

**Comment by symbios24** [comment] 2018-06-22 10:51
same problem happens on raspberry pi 2 kernel panic in 10 times i remove the power one time boot ng
very annoying waiting for a fix

**Comment by maxnet** [comment] 2018-07-15 00:33
Could folks that were experiencing this problem with the previous Berryboot version, test if 2018-07-15 works better?
Thanks.

**Comment by maxnet** [comment] 2018-07-19 15:58
Assuming fixed

**Closed as completed by maxnet** 2018-07-19 15:58 UTC
