### ISSUE TITLE
Berryboot 20180216 and startup messages

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#476] opened 2018-02-17 17:00 UTC
Thanks so much for new build!

Meanwhile, it seems initial onscreen startup messages are now disabled (Mounting image... ).
It's certainly neater for end-users, but it makes development/debugging more tricky: how can we re-enable them when needed?

Thanks.

**Comment by maxnet** [comment] 2018-03-14 21:09
Please check if the issue is still present in 20180314
Does work for me.

**Comment by macmpi** [comment] 2018-03-14 22:14
Thanks for the new build.
Just tested again, and I still can't see anymore echoed init messages such as [this one](https://github.com/maxnet/berryboot/blob/berryboot2015/buildroot-2015.02/package/berrybootgui2/init#L94)

Maybe sth in this commit https://github.com/maxnet/berryboot/commit/642187ce0c3925f58aa83c6fb53e219e0b2b17d1 broke it

**Comment by maxnet** [comment] 2018-03-14 22:24
Do you have any special `console=something` settings in `cmdline.txt` for serial console or similar things?

**Comment by macmpi** [comment] 2018-03-14 22:28
nope, and did not change from previous setup.
I see messages from image startup sequence (like raspbian lite), but I do not see earlier messages from berryboot init

**Comment by maxnet** [comment] 2018-03-14 22:33
What type of Pi is it?

![20180314_233213](https://user-images.githubusercontent.com/1123701/37434509-161a84fe-27e0-11e8-91b4-0331831fd3dd.jpg)

On a Pi 3

**Comment by macmpi** [comment] 2018-03-14 22:45
hum... I'm jealous now
I'm on PiZero
I only see the cursor on 5th line, but nothing before.

**Comment by maxnet** [comment] 2018-03-14 23:04
Ah, you're right.
Managed to reproduce it on a Pi Zero.
Not sure why.

**Comment by maxnet** [comment] 2018-03-14 23:16
For some reason the kernel now seems to default to using serial console as terminal for Pi 1 kernel configurations.
As a workaround for now, append to cmdline.txt (on same line as other options): console=tty1

**Comment by macmpi** [comment] 2018-03-15 08:27
Thanks for the quick workaround: this helps.
Hope Foundation guys will address the root cause as per your opened issue.

**Comment by macmpi** [comment] 2018-03-18 09:18
looks like the bug has been fixed in 4.14.27 now

**Comment by maxnet** [comment] 2018-03-22 21:14
Fixed in berryboot-20180322

**Closed as completed by maxnet** 2018-03-22 21:14 UTC

**Comment by macmpi** [comment] 2018-03-23 06:14
thanks!
